<?php

namespace CCDNForum\ForumBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdminBoardController__JMSInjector
{
    public static function inject($container) {
        $instance = new \CCDNForum\ForumBundle\Controller\AdminBoardController();
        return $instance;
    }
}
