<?php

namespace Jlfa\WebSiteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class WebSiteController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Jlfa\WebSiteBundle\Controller\WebSiteController();
        return $instance;
    }
}
