<?php

namespace Proxies\__CG__\CCDNForum\ForumBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Category extends \CCDNForum\ForumBundle\Entity\Category implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'name', 'listOrderPriority', 'readAuthorisedRoles', 'forum', 'boards');
        }

        return array('__isInitialized__', 'id', 'name', 'listOrderPriority', 'readAuthorisedRoles', 'forum', 'boards');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Category $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function forumName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'forumName', array());

        return parent::forumName();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getListOrderPriority()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListOrderPriority', array());

        return parent::getListOrderPriority();
    }

    /**
     * {@inheritDoc}
     */
    public function setListOrderPriority($listOrderPriority)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setListOrderPriority', array($listOrderPriority));

        return parent::setListOrderPriority($listOrderPriority);
    }

    /**
     * {@inheritDoc}
     */
    public function getReadAuthorisedRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReadAuthorisedRoles', array());

        return parent::getReadAuthorisedRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setReadAuthorisedRoles(array $roles = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReadAuthorisedRoles', array($roles));

        return parent::setReadAuthorisedRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function hasReadAuthorisedRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasReadAuthorisedRole', array($role));

        return parent::hasReadAuthorisedRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function isAuthorisedToRead(\Symfony\Component\Security\Core\SecurityContextInterface $securityContext)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAuthorisedToRead', array($securityContext));

        return parent::isAuthorisedToRead($securityContext);
    }

    /**
     * {@inheritDoc}
     */
    public function getForum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForum', array());

        return parent::getForum();
    }

    /**
     * {@inheritDoc}
     */
    public function setForum(\CCDNForum\ForumBundle\Entity\Forum $forum = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForum', array($forum));

        return parent::setForum($forum);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoards()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoards', array());

        return parent::getBoards();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoards(\Doctrine\Common\Collections\ArrayCollection $boards = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoards', array($boards));

        return parent::setBoards($boards);
    }

    /**
     * {@inheritDoc}
     */
    public function addBoard(\CCDNForum\ForumBundle\Entity\Board $board)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBoard', array($board));

        return parent::addBoard($board);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBoard(\CCDNForum\ForumBundle\Entity\Board $board)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBoard', array($board));

        return parent::removeBoard($board);
    }

}
