parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     5433
    database_name:     jlfa
    database_user:     postgres
    database_password: admin


    locale:            fr
    locales: fr|en|de
    secret:            ThisTokenIsNotSoSecretChangeIt
    
    java_path: C:\Program Files (x86)\Java\jre7\bin\java.exe
    
    sdzblog.nombre_par_page: 5
    sdzblog.dest_email:      vous@vous.Com

    akismet_key: votre_cle
    akismet_url: votre_site
    
    nombre_par_page: 5
    
    kernel.debug : true

   