root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/
        permanent: true

jlfa_web_site:
    resource: "@JlfaWebSiteBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: %locales%

SdzBlogBundlePrefix:
    resource: "@SdzBlogBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/blog
    requirements:
        _locale: %locales%
    
userbundle:
    resource: "@SdzUserBundle/Resources/config/routing.yml"
    prefix:   /

# Les imports pour FOSUB :
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /{_locale}
    requirements:
        _locale: %locales%
    

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/change-password
    
    
_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"
    
_apy_jsformvalidation:
    resource: "@APYJsFormValidationBundle/Resources/config/routing/routing.yml"


jlfa_forum:
     resource: "@JlfaForumBundle/Resources/config/routing.yml"
     
jlfa_apy_js_form_validation:
    resource: "@JlfaAPYJsFormValidationBundle/Resources/config/routing.yml"
    prefix:   /
