services:
    # custom forms for userbundle
    sdz_user.registration.form.type:
        class: Sdz\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sdz_user_registration }
            
    sdz_user.edit.form.type:
        class: Sdz\UserBundle\Form\Type\ProfileEditFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sdz_user_edit_profile }
            
    # cutsom contrain to valid the adresse
    sdzblog.validator.sdzblog_isAdresseValid:    
        class:     Sdz\UserBundle\Validator\IsAdresseValidValidator
        tags:
            - { name: validator.constraint_validator, alias: sdzblog_isAdresseValid }
    
            
            
    # FOS SUBSCRIBER
    # update the map when user edit profile and when the registration process is confirmed
    sdzblog.updatemap:
        class: Sdz\UserBundle\Listener\MapUpdaterListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_subscriber }
            