services:
    
    

    sdz_user.registration.form.type:
        class: Sdz\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sdz_user_registration }
            
    sdz_user.edit.form.type:
        class: Sdz\UserBundle\Form\Type\ProfileEditFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sdz_user_edit_profile }
            
            
    sdzblog.validator.sdzblog_isAdresseValid:    
        class:     Sdz\UserBundle\Validator\IsAdresseValidValidator
        tags:
            - { name: validator.constraint_validator, alias: sdzblog_isAdresseValid }
            
            
    sdzblog.updatemap:
        class: Sdz\UserBundle\Listener\MapUpdater
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: fos_user.registration.confirmed, method: updateMap }
            - { name: doctrine.event_listener, event: fos_user.profile.edit.success, method: updateMap }
            
    sdzblog.postcreate:
        class: Sdz\UserBundle\Listener\UserACL
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: fos_user.registration.success, method: addACL }