CCDNForumForumBundle:
    resource: "@CCDNForumForumBundle/Resources/config/routing.yml"
    
forum_jlfa_homepage:
    pattern: /forum/extendscript-library
    defaults: { _controller: CCDNForumForumBundle:UserCategory:index, _locale: en, forumName: extendscript-library }