<?php

namespace EnhancedProxy668e1049_d946947553b7cbf9f4e7ff596a57ff3b311e10bd\__CG__\Sdz\BlogBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BlogController__JMSInjector
{
    public static function inject($container) {
        require_once '/Applications/MAMP/htdocs/jlfa/app/cache/dev/jms_diextra/proxies/EnhancedProxy668e1049_d946947553b7cbf9f4e7ff596a57ff3b311e10bd-__CG__-Sdz-BlogBundle-Controller-BlogController.php';
        $b = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Sdz\\BlogBundle\\Controller\\BlogController' => array('supprimerAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'addPostAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy668e1049_a0383949c41331eb6ea66f996ed9d59b04253d37\__CG__\Sdz\BlogBundle\Controller\BlogController();
        $instance->__CGInterception__setLoader($b);
        return $instance;
    }
}
