<?php

namespace Jlfa\APYJsFormValidationBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ValidationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Jlfa\APYJsFormValidationBundle\Controller\ValidationController();
        return $instance;
    }
}
