services:
  
    # validators
    
    # check if the user post more than one comment each 45 secondes
    sdzblog.validator.antiflood:                                
        class:     Sdz\BlogBundle\Validator\AntiFloodValidator  
        arguments: ["@request", "@doctrine.orm.entity_manager"] 
        scope:     request                                      
        tags:
            - { name: validator.constraint_validator, alias: sdzblog_antiflood }  # alias to find the service
    
    # check if the comment content has more than 3 links
    sdzblog.validator.antispam:                                
        class:     Sdz\BlogBundle\Validator\AntiSpamValidator  
        tags:
            - { name: validator.constraint_validator, alias: sdzblog_antispam }
 